###
GET http://localhost:3003/bmi?height=180&weight=85

###
GET http://localhost:3003/bmi?height=180

###
POST http://localhost:3003/exercises HTTP/1.1 
content-type: application/json

{
  "daily_exercises": [1, 0, 2, 0, 3, 0, 2.5],
  "target": 2.5
}

###
POST http://localhost:3003/exercises HTTP/1.1 
content-type: application/json

{
  "daily_exercises": [1, 0, 2, 0, 3, 0, 2.5],
  "target": "a"
}

###
GET http://localhost:3001/api/patients

###
GET http://localhost:3001/api/diagnoses

###
GET http://localhost:3001/api/patients/d2773336-f723-11e9-8f0b-362b9e155667


###
POST http://localhost:3001/api/patients HTTP/1.1 
content-type: application/json

{
  "name": "Testinen testaaja",
  "dateOfBirth": "2022-12-31",
  "ssn": "123-456-789",
  "gender": "other",
  "occupation": "automatic tester" 
}